name: Sync from upstream (lobehub/lobe-chat)

on:
  schedule:
    - cron: '0 2 * * *'  # Every day at 2:00 AM UTC
  workflow_dispatch:     # Allow manual runs from Actions tab

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your fork
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Add upstream remote
        run: git remote add upstream https://github.com/lobehub/lobe-chat.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout main
          git merge upstream/main --no-edit || echo "No changes to merge"

      - name: Push changes to your fork
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '🔄 Auto-sync from lobehub/lobe-chat'
          branch: main
